# Google Cloud Build configuration for Opus Agent (Updated 2024)
# This file defines the build steps for deploying to Cloud Run with WebSocket optimization

steps:
  # Build the Docker image with multi-platform support
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t' 
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:latest'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:latest'

  # Deploy to Cloud Run with WebSocket optimization
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'opus-agent'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--concurrency=100'
      - '--max-instances=20'
      - '--min-instances=1'
      - '--cpu-boost'
      - '--execution-environment=gen2'
      - '--set-env-vars=ENV=production,PORT=8000,HOST=0.0.0.0'

# Store images in Artifact Registry (replacing deprecated Container Registry)
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:latest'

# Timeout for the entire build
timeout: '1800s'

# Options for the build with faster machine type
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Set environment variables for Cloud Build
substitutions:
  _REGION: 'us-central1' 