# Google Cloud Build configuration for Opus Agent
# This file defines the build steps for deploying to Cloud Run with WebSocket optimization
# gcloud builds submit --tag us-central1-docker.pkg.dev/opusagent/cloud-run-source-deploy/opus-agent:latest .

steps:
  # Build the Docker image with multi-platform support
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t' 
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$BUILD_ID'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:latest'

  # Deploy to Cloud Run with enhanced configuration and Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'opus-agent'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=3600'
      # For free tier validation with single call at a time
      - '--concurrency=1'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--no-cpu-boost'
      - '--cpu-throttling'
      - '--execution-environment=gen2'
      - '--set-env-vars=ENV=production,PORT=8000,HOST=0.0.0.0,LOG_LEVEL=INFO'
      - '--update-env-vars=OPUSAGENT_USE_MOCK=false,USE_LOCAL_REALTIME=false'
      - '--set-secrets=OPENAI_API_KEY=openai-api-key:latest'
      - '--ingress=all'
      # VPC connector removed for initial deployment - add back if needed
      # - '--vpc-connector=projects/$PROJECT_ID/locations/us-central1/connectors/opus-vpc-connector'
      # - '--vpc-connector-egress-settings=PRIVATE_RANGES_ONLY'

# Store images in Artifact Registry (replacing deprecated Container Registry)
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/opus-agent:latest'

# Timeout for the entire build
timeout: '1800s'

# Options for the build with faster machine type
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: '100'
  
# Set environment variables for Cloud Build
# Note: Region is hardcoded to us-central1 in the build steps 