version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    environment:
      - OPUSAGENT_USE_MOCK=false
      - OPUSAGENT_MOCK_SERVER_URL=ws://localhost:8080
      - USE_LOCAL_REALTIME=false
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO 